### ISSUE TITLE
Remove mouse red dot cursor when in prod (not debug)

### ISSUE THREAD

**Issue by matthias4217** [debiantarte/feudal-overlords#19]

**Comment by debiantarte** [comment]
we could also just remove it entirely, no ?

**Comment by debiantarte** [comment]
Tried to do it in commit d08aaa40cf39dadeaa58a822c13ab6c51e06d21c but didn't manage to make it appear only in debug... I thought VS implemented a variable DEBUG ?

**Comment by matthias4217** [comment]
I've no idea. At least, we'll keep this issue to think about removing it just before sending the commit !
