### ISSUE TITLE
Display result of attack clearly

### ISSUE THREAD

**Issue by matthias4217** [debiantarte/feudal-overlords#20]
not in the terminal

**Comment by matthias4217** [comment]
Maybe make a window pop

**Comment by debiantarte** [comment]
there are notifications now, could be enough

**Comment by matthias4217** [comment]
Yup, awesome ! Also it's still maybe buggy ?
Turn 1: Princess Luna conquers AI
...
Turn 2: AI move troops to Princess Luna capital, but it shows as AI conquered Princess Luna.
And I think the movement is broken again. I thought I had fixed it.

**Comment by debiantarte** [comment]
Ah yes, we either need to change the return type of attack functions to be able to display different notifications when it's just a movement, or we could do a more decoupled notification system but we may not have enough time for that :/

**Comment by debiantarte** [comment]
But on the movement and conquest side, everything seems fine on my end. Weird.

**Comment by debiantarte** [comment]
Should be pretty much sufficient now I guess..?

**Comment by debiantarte** [comment]
Notification still need to be redone !

**Comment by debiantarte** [comment]
quite done !
