### ISSUE TITLE
Implement adjacency for attacks

### ISSUE THREAD

**Issue by matthias4217** [debiantarte/feudal-overlords#23]

**Comment by debiantarte** [comment]
i think it's done ?

**Comment by debiantarte** [comment]
It would be better with an adjacency graph to detect adjacency in an accurate way

**Comment by matthias4217** [comment]
So now we've got an adjacency list !

**Comment by debiantarte** [comment]
So at this point we use first delaunay triangulation to detect adjacent territories and use the old rectangles-based detection, because on the edges there were some weird bugs related to the fact that the voronoi diagram is virtually "infinite"

**Comment by debiantarte** [comment]
looks done
