### ISSUE TITLE
Adds Player object

### ISSUE THREAD

**Issue by matthias4217** [debiantarte/feudal-overlords#5]
* [x] Inherits from Lord
  * [ ] void attack(Territory)
  * [ ] void buy(Territory)
  * [ ] void negociateWith(Lord)
  * [ ] void threaten(Lord)
  * [ ] void raiseTroops(Territory)

**Comment by debiantarte** [comment]
The functions to attack, buy, etc... will not be implemented in Player, but either right in Board or in an input manager

**Comment by matthias4217** [comment]
It might not be totally finished, but the rest would be moved to separate issues.
